POST http://{{host}}/order/api/v1/order
Content-Type: application/json
Authorization: {{access-token}}

{
  "route": {
    "from": "NVK",
    "to": "Библиотечная 45"
  },
  "price": 100,
  "transportId": "b5f08de3-bbf8-47fc-b567-67211716a62d",
  "timeStart": "2023-12-18T11:28:16.669Z",
  "startFreeSeatCount": 4
}
