POST http://{{host}}/order/api/v1/order
Content-Type: application/json
Authorization: {{access-token}}

{
  "route": {
    "from": "NVK",
    "to": "Библиотечная 45"
  },
  "price": 100,
  "transportId": "7c932273-e83a-4f93-834b-6f52d1152d6f",
  "timeStart": "2023-11-18T11:28:16.669Z",
  "startFreeSeatCount": 4
}
