POST http://localhost:3000/profile/api/v1/data/user
Content-Type: application/json
Authorization: {{access-token}}

{
    "isDriver": true,
    "paymentMethods": [
        {
            "phone": "79122602002",
            "bank": 1
        }
    ]
}
